name: acceptance-tests

on:
  schedule:
    - cron: "0 10 * * *"

jobs:

  acceptance-tests:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "20.12.2"

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        continue-on-error: true
        id: cypress
        run: npm run test:run

      - name: Check on failures
        if: steps.cypress.outcome != 'success'
        run: exit 1

 
